apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: __TEAM_NAME__-helm-repo
  namespace: flux-config
  labels:
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  type: oci
  interval: 3m0s
  url: oci://${APPLICATION_ACR_NAME}.azurecr.io/helm
  provider: azure